### ISSUE TITLE
Getting IndexOutOfBoundsException: 0 when running "updatecassandra clean run"

### ISSUE THREAD

**Issue by travisfinch** [Netflix/osstracker#11] opened 2016-06-08 23:12 UTC
I am following the docs here: https://github.com/Netflix/osstracker/tree/documentation/osstracker-docs

I am hitting a failure when I get to the step to populate Cassandra and ElasticSearch. Here is the exception:

$ ./gradlew -PACTION=updatecassandra clean run
Inferred project: osstracker, version: 0.1.0-SNAPSHOT
[buildinfo] Not using buildInfo properties file for this build.
:osstracker-console:clean
:osstracker-scraper:clean
:osstracker-scraper:compileJava UP-TO-DATE
:osstracker-scraper:compileScala
:osstracker-scraper:processResources
:osstracker-scraper:classes
:osstracker-scraper:runScraper
remaining calls 4969
2016-06-08 18:05:43 INFO  NettyUtil:83 - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2016-06-08 18:05:44 INFO  DCAwareRoundRobinPolicy:95 - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2016-06-08 18:05:44 INFO  Cluster:1475 - New Cassandra host /10.115.68.100:9042 added
2016-06-08 18:05:45 DEBUG GithubScraper:29 - cassRepos = List()
2016-06-08 18:05:46 DEBUG GithubScraper:34 - githubRepos = List(<REMOVED>)
Exception in thread "main" java.lang.IndexOutOfBoundsException: 0
	at scala.collection.mutable.ListBuffer.apply(ListBuffer.scala:126)
	at com.netflix.oss.tools.osstrackerscraper.GithubScraper.updateElasticSearch(GithubScraper.scala:66)
	at com.netflix.oss.tools.osstrackerscraper.RunGithubScraper$.main(GithubScraper.scala:219)
	at com.netflix.oss.tools.osstrackerscraper.RunGithubScraper.main(GithubScraper.scala)

**Comment by travisfinch** [comment] 2016-06-09 20:35
I spent a little bit of time looking at the code even though I am not too familiar with Scala, and I think I see what is going on here. Please correct me if I am wrong.

docsList (which is the variable causing the IndexOutOfBoundsException) is gets populated in the loop here: https://github.com/Netflix/osstracker/blob/master/osstracker-scraper/src/main/scala/com/netflix/oss/tools/osstrackerscraper/GithubScraper.scala#L42

This loop never executes because sortedGHRepos has no elements. Why? Because it gets populated based off of what is in Cassandra.

https://github.com/Netflix/osstracker/blob/master/osstracker-scraper/src/main/scala/com/netflix/oss/tools/osstrackerscraper/GithubScraper.scala#L36

This is the first time I am running the tool, so Cassandra is empty. Is there a step I am missing from the docs here? https://github.com/Netflix/osstracker/tree/documentation/osstracker-docs

**Comment by travisfinch** [comment] 2016-06-09 20:42
Okay, I think I got this working. I manually updated the action arg in https://github.com/Netflix/osstracker/blob/master/osstracker-scraper/build.gradle to run updatecassandra and it completed.

I had to do the same thing for the environment variables also, which is why I do not have them listed in my original command.

**Comment by aspyker** [comment] 2016-06-29 07:18
I believe we fixed a similar bug here:

https://github.com/Netflix/osstracker/commit/0b54ccf3ece9967f37a982f7ddaf12be8ede4f30

If you believe this is fixed now, can you close?

**Comment by aspyker** [comment] 2016-07-11 02:04
Closing.  Please re-open if you still see the bug with latest code as you said it wasn't reproduceable and I've cleaned up the code a good bit since then.

**Closed by aspyker** 2016-07-11 02:04 UTC
